package models.intercom.bulk

import play.api.libs.json.{JsValue, Json, Writes}

/**
  * The intercom bulk obj for bulk updates
  * @param items: the data to update
  * @param optJobId: the job id generated by intercom, if supplied, data is appended to the current bulk
  */
case class Bulk(
               items: List[Item],
               optJobId: Option[String] = None
               )

object Bulk {

  implicit val jsonWrites: Writes[Bulk] = new Writes[Bulk] {
    override def writes(b: Bulk): JsValue = Json.obj(
      "items" -> b.items
    ) ++ {
      if (b.optJobId.isDefined) Json.obj("job" -> Json.obj("id" -> b.optJobId.get))
      else Json.obj()
    }
  }

}